spring:
  application:
    name: auth-service
#  mvc:
#    servlet:
#      path: /auth-service

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

